# Generated by Django 5.0.3 on 2024-03-27 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_refreshtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='registered',
        ),
    ]
