# Generated by Django 5.0.3 on 2024-03-27 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_account_registered'),
        ('contact_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpamReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spam_reason', models.CharField(choices=[('UN', 'Unknown'), ('AD', 'Advertisment or telemarketing'), ('BK', 'Loans or EMI'), ('FR', 'Fraud')], default='UN', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_management.contact')),
                ('spam_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.account')),
            ],
        ),
    ]
