# Generated by Django 5.0.3 on 2024-03-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_management', '0002_spamreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spamreport',
            name='spam_reason',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Advertisment or telemarketing', 'Advert'), ('Loans or EMI', 'Bank'), ('Fraud', 'Fraud')], default='Unknown', max_length=30),
        ),
    ]
